logging:
  level:
    org.springframework: ERROR
    com.ezbob.logservice: INFO
  file: service-shuffle.log
server:
  port: 8082
spring:
  application:
    name: service-shuffle
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
limitOfFeed: 20
selectionLimitFeed: 50
app:
  logApplicationName: service-log
